all:
  hosts:
    foo.example.com:
  children:
    drservers:
      hosts:
        # Digital Rebar server
        192.168.1.168:

    win_hosts:
      hosts:
        192.168.1.182:  # Silicon surfer

    backup_servers:
      hosts:
        10.14.3.104

