
- name: Configure Pi cluster hosts
  hosts: all

  vars:
#    ansible_become: true
#    ansible_become_method: su

  tasks:
    - name: ping the host
      ansible.builtin.ping:

    - name: Debug - Show remote env
      debug:
        var: ansible_env

    - name: Create the nfs directory if it does not exist
      ansible.builtin.file:
        path: /nfs/data
        state: directory
        mode: '0755'
      become_user: pi


    - name: Mount an NFS volume
      ansible.posix.mount:
        src: 192.168.10.2:/backup
        path: /nfs/data
        opts: rw,sync,hard
        boot: true
        state: mounted
        fstype: nfs
      become_user: pi